/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.awt.Color;
import javax.swing.text.DefaultHighlighter;
import javax.swing.text.Highlighter;
import javax.swing.text.Highlighter.HighlightPainter;

/**
 *
 * @author admin
 */
public class MainInterface extends javax.swing.JFrame {

    /**
     * Creates new form MainInterface
     */
    public MainInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "市场", "夜市", "城市", "各国", "各地", "各家", "各种各样", "亮亮我去超市买东西" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 0, 24)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("方方亮亮，你去哪儿\n亮亮我去超市买东西\n方方我昨天也去了超市那儿的东西可多了\n亮亮那儿有什么呢\n方方有五颜六色的练习本各种各样的笔还有很多漂亮的\n尺子小刀和书包\n亮亮那儿有卡片吗我想买几张卡片\n方方：有。有很多漂亮的卡片，还有很多好玩儿的玩具。你\n看，我的新书包。\n亮亮：颜色真漂亮啊！上面这行小小的英文字是……\n方方：Made in China.中国制造的。这个书包是从中国进口的。\n亮亮：我也想买一个这么漂亮的书包。你是在哪里买的？\n方方：就在前面的超市。\n");
        jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextArea1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
 if(!evt.getValueIsAdjusting())
 {        
        try{
        String text=jList1.getSelectedValue();
 Sample sample=new Sample();
String soundFilePath=sample.getSoundFilePath(text);
       MP3 mp3 = new MP3(soundFilePath);
        mp3.play();
         System.out.println(text);
 }
 catch(Exception e)
 {
     e.printStackTrace();
 }
 }
    }//GEN-LAST:event_jList1ValueChanged

private void playText(String text)
{
 try{
 Sample sample=new Sample();
String soundFilePath=sample.getSoundFilePath(text);
       MP3 mp3 = new MP3(soundFilePath);
        mp3.play();
 }
 catch(Exception e)
 {
     e.printStackTrace();
 }   
}
        
    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
 try{
        String textAll=jTextArea1.getText();
        int currentCaretPosition = jTextArea1.getCaretPosition();
        /*
      String firstPartString=textAll.substring(0,currentCaretPosition);
      int positionOfWhiteSpace1=firstPartString.lastIndexOf("\n");
      if(positionOfWhiteSpace1<0)
      {
          positionOfWhiteSpace1=0;
      }
      System.out.println(firstPartString+"positionOfWhiteSpace1:"+positionOfWhiteSpace1);
      
      String secondPartString=textAll.substring(currentCaretPosition);
      int positionOfWhiteSpace2=currentCaretPosition+secondPartString.indexOf("\n");
   System.out.println("positionOfWhiteSpace2:"+positionOfWhiteSpace2);      
      //   System.out.println(firstPartString);
       // String text=textAll.substring(currentCaretPosition,currentCaretPosition+1);
        String text=textAll.substring(positionOfWhiteSpace1, positionOfWhiteSpace2-1);
        */
        String text=textAll.substring(currentCaretPosition,currentCaretPosition+1);
        System.out.println(text);
        
        if(text.trim().length()>0)
        {
        playText(text);
        Highlighter highlighter = jTextArea1.getHighlighter();
        highlighter.removeAllHighlights();
      HighlightPainter painter =      new DefaultHighlighter.DefaultHighlightPainter(Color.LIGHT_GRAY);
      highlighter.addHighlight(currentCaretPosition, currentCaretPosition+1, painter );
        }
        else
        {
         System.out.println("nothing selected.");   
        }
      
 /*       
 Sample sample=new Sample();
String soundFilePath=sample.generateSoundFile(text);
       MP3 mp3 = new MP3(soundFilePath);
        mp3.play();
   */     
 }
 catch(Exception e)
 {
     e.printStackTrace();
 }
    }//GEN-LAST:event_jTextArea1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainInterface().setVisible(true);
            }
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
