/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Baoshan
 */
public class readChinese extends javax.swing.JFrame {
String listOfWords="红灯 绿灯 路灯 灯光 开灯 关灯 街灯 街头 街市 上街 街道 道路 又宽又大 很宽 交通 交通车 交通灯 交通工具 通过 来往 人来车往 弟弟 妹妹 拉拉手 手拉手 停车 停电 停水 停放 停一停\n" +
" 店 童 话 故 报 等 吃 饭 现 课 拿 呢 付 钱\n" +
" 书店 面包店 花店 饭店 儿童 童年 童话 说话 讲话 故事 儿童故事 故事书 画报 课本 课文 课间 上课 下课 听课 讲课 拿来 拿走 现在 等车 等人 等一会儿 吃饭 做饭 早饭 午饭 付钱 用钱 花钱 钱包\n" +
" 医 院 感 冒 烧 带 病 护 士 量 温 针 药 就\n" +
" 医院 医生 中医 西医 出院 学院 感冒 感动 感人 感谢 感想 带书 带笔 带钱 病人 病房 生病 看病 护士 量体温 发烧 烧水 烧火 开药 药水 药店 药方 药房 吃药 中药 西药 猜 鼻 眼 睛 只 嘴 "
        + " 边 传 粉 采 蜜 朵 劳 动 猜一猜 猜想 鼻子 眼睛 一双眼睛 一只眼睛 一只小鸟 一只手 耳朵 一张嘴 嘴里 嘴边 河边 上边 下边 里边 外边 边上 边说边写 边想边说 边走边说 传花粉"
        + " 传说 传真 花粉 面粉 粉笔 采蜜 花蜜 劳动 爱劳动 动作 动脑 动身 动物 知 变 成 汽 飘 冷 珠 掉 候 睡 觉 跑 跳 知道 变成 变老 变小 变大 变长 变黑 变白 汽水 汽车 一朵花 "
        + "一朵云 飘走 飘来飘去 飘动 冷天 太冷 冷风 水珠 雨珠 掉下来 时候 有时候 睡觉 睡着了 跑出去 跑出来 又跑又跳 跳动 跳高 跳远 满 猫 糖 狗 盐 争 自 己 兔 过 尝 甜 咸 凉 "
        + " 满地 满口 满嘴 小猫 小黑猫 小白猫 小花猫 一只猫 吃糖 糖水 放糖 白糖 小狗 小黑狗 小白狗 小花狗 一只狗 放盐 盐水 别争了 争着说 争着写 争着做 自己 兔子 一只兔子 过来 "
        + " 过去 走过 路过 过年 过生日 尝尝 尝一尝 很咸 凉快 凉水 诗 首 静 床 疑举望 低 乡 楼 千 更 层 古诗 诗歌 诗人 写诗 三首诗 很静 静静地想 静静地坐着 起床 两张床 床头 床边 "
        + " 疑问 举手 低头 故乡 乡下 楼上 楼下 一楼 二楼 三层楼 一千 一千二百 三千五百六十 更好 更多 更少 更大 更小 举头望明月 低头思故乡 欲 穷千里目，更上一层楼 壶 盖 英 科 "
        + " 奇怪气 冲 让 常 试 验 机 位 水壶 一壶水 壶盖 英国 英国人 英语 科学 科学家 奇怪 生气 冲出来 冲上去 冲下来 让开 让一让 常常 常用 试验 试一试 机器 手机 飞机 洗衣机 "
        + " 电视机 一位老师 一位科学家 造 纸 代 把 竹 片 便 元 决 皮 破 布 打 干 之 造纸 白纸 一张纸 现代 古代 竹子 竹片 方便 公元 决定 决心 树皮 皮包 破布 白布 花布 打破 打开 "
        + " 打电话 干果 之一 之中 龟赛乌 步 爬 回 得 意 慢 追 仍 然 第 乌龟 乌云 比赛 赛跑 跑步 一步一步地走 爬山 爬树 回头 回来 回去 回家 回国 很慢 爬得很慢 走得很慢 跑得很慢 得意 得到 意思 意见 追上 仍然 然后 第一名 第十课";

ArrayList aList= new ArrayList(Arrays.asList(listOfWords.split(" ")));
int index=0;
    /**
     * Creates new form readChinese
     */
    public readChinese() {
        initComponents();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        status = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(jLabel1.getFont().deriveFont(jLabel1.getFont().getStyle() | java.awt.Font.BOLD, jLabel1.getFont().getSize()+263));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jButton1.setText("next>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("< Prev");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        status.setText("status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton2)
                .addGap(380, 380, 380)
                .addComponent(status)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 401, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(status))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        index++;
        if(index>aList.size()-1)
            index=0;
        displayNew();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        index--;
        if(index<0)
            index=aList.size()-1;
        displayNew();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       int labelWidth=jLabel1.getWidth();
       if(evt.getX()<labelWidth/2)
       {
          index--;
        if(index<0)
            index=aList.size()-1;   
       }
       else
       {               
        index++;
        if(index>aList.size()-1)
            index=0;
       }
        displayNew();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void displayNew()
    {
        String newWord=((String)aList.get(index)).trim();
              jLabel1.setText(newWord);
              status.setText(index+"/"+aList.size());

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(readChinese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(readChinese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(readChinese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(readChinese.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new readChinese().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel status;
    // End of variables declaration//GEN-END:variables
}
